/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface MulticallInterface extends utils.Interface {
  functions: {
    "execute(uint256,uint256,address[],bytes[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "execute"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<BytesLike>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;

  events: {};
}

export interface Multicall extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MulticallInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execute(
      gasLimit: PromiseOrValue<BigNumberish>,
      sizeLimit: PromiseOrValue<BigNumberish>,
      addrs: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[], string[]] & {
        blockNumber: BigNumber;
        statuses: BigNumber[];
        results: string[];
      }
    >;
  };

  execute(
    gasLimit: PromiseOrValue<BigNumberish>,
    sizeLimit: PromiseOrValue<BigNumberish>,
    addrs: PromiseOrValue<string>[],
    datas: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber[], string[]] & {
      blockNumber: BigNumber;
      statuses: BigNumber[];
      results: string[];
    }
  >;

  callStatic: {
    execute(
      gasLimit: PromiseOrValue<BigNumberish>,
      sizeLimit: PromiseOrValue<BigNumberish>,
      addrs: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[], string[]] & {
        blockNumber: BigNumber;
        statuses: BigNumber[];
        results: string[];
      }
    >;
  };

  filters: {};

  estimateGas: {
    execute(
      gasLimit: PromiseOrValue<BigNumberish>,
      sizeLimit: PromiseOrValue<BigNumberish>,
      addrs: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      gasLimit: PromiseOrValue<BigNumberish>,
      sizeLimit: PromiseOrValue<BigNumberish>,
      addrs: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
